### ISSUE TITLE
Missing MySQL.Data.dll

### ISSUE THREAD

**Issue by schilder** [JaredTS486/Inventory-Management#9]
Deleted repository on laptop and redownloaded repository.  In addition to the two other issues, missing My.SQL.Data.dll now too.

**Comment by JaredTS486** [comment]
If the .dll file is missing from your debug or release folder then let me
know. Otherwise you probably don't have my sol installed and you will need
to manually set the reference to the new location of the mysql.data.dll
file.

**Comment by JaredTS486** [comment]
i pushed the DLL files in m latest push, you can reference to those.
